# Generated by Django 3.1.6 on 2021-02-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('zoom_link', models.CharField(max_length=600, null=True)),
            ],
        ),
    ]
