# Generated by Django 3.1.6 on 2021-02-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210216_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='icon',
            field=models.CharField(choices=[('choice1', 'self_improvement'), ('choice2', 'spa'), ('choice3', 'piano'), ('choice4', 'fireplace'), ('choice5', 'coffee'), ('choice6', 'grass'), ('choice7', 'brightness_2'), ('choice8', 'auto_awesome'), ('choice9', 'brightness_4'), ('choice0', 'palette')], default='choice6', max_length=60),
        ),
    ]
