# Generated by Django 3.1.6 on 2021-02-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_event_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='icon',
            field=models.CharField(choices=[('self_improvement', 'self_improvement'), ('spa', 'spa'), ('piano', 'piano'), ('fireplace', 'fireplace'), ('coffee', 'coffee'), ('grass', 'grass'), ('brightness_2', 'brightness_2'), ('auto_awesome', 'auto_awesome'), ('brightness_4', 'brightness_4'), ('palette', 'palette')], default='choice6', max_length=60),
        ),
    ]
