# Generated by Django 3.1.6 on 2021-02-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210217_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='zoom_link',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
