# Generated by Django 3.1.6 on 2021-02-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210217_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='zoom_link',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
